{{- $secret := .Values.secret | default dict }}
{{- if $secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{- range $k, $v := ($secret.data | default dict) }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
