{{- $secret := .Values.secret | default dict }}
{{- if $secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  GIT_URI: {{ $secret.gitUri | quote }}
  GIT_USERNAME: {{ $secret.gitUsername | quote }}
  GIT_PASSWORD: {{ $secret.gitPassword | quote }}
{{- end }}
