{{- range $name, $worker := .Values.workers }}
{{- $configmap := $worker.configmap | default dict }}
{{- if and $worker.enabled $configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-config
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
    component: {{ $name }}
data:
  {{- range $k, $v := ($configmap.data | default dict) }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
