{{- range $name, $worker := .Values.workers }}
{{- $secret := $worker.secret | default dict }}
{{- if and $worker.enabled $secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $name }}-secret
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
    component: {{ $name }}
type: Opaque
stringData:
  {{- range $k, $v := ($secret.data | default dict) }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
